const GalleryActionTypes = {
  FETCH_IMAGES_START: "FETCH_IMAGES_START",
  FETCH_IMAGES_SUCCESS: "FETCH_IMAGES_SUCCESS",
  FETCH_IMAGES_FAILURE: "FETCH_IMAGES_FAILURE"
};

export default GalleryActionTypes;
